Change xml file
idpay/rsform pull request #4
Opened 2020-08-19 14:40 UTC by mnbp1371

2020-08-19 14:40 UTC, mnbp1371 commented
@vispamir

2020-08-20 12:02 UTC, vispamir requested changes

2020-08-20 12:02 UTC, vispamir commented on rsfpidpay/rsfpidpay.xml
> +	<author>mnbp1371</author>
Change author parameters idpay info.

2020-08-20 12:02 UTC, vispamir commented on rsfpidpay/rsfpidpay.xml
> +	<authorEmail>mohammadnabipour1371@gmail.com</authorEmail>
Change to support@idpay.ir

2020-08-22 05:08 UTC, mnbp1371 commented
Change author email

@vispamir

2020-08-22 05:18 UTC, mnbp1371 commented
Change author parameters
@vispamir

2020-08-23 19:43 UTC, merged